### ISSUE TITLE
pool: Build a persistent, multi-client, redis-backed mempool

### ISSUE THREAD

**Issue by dancoombs** [alchemyplatform/rundler#115]
**Describe the feature**
We need a persistent mempool to handle bundler crashes and upgrades. This can be done in 2 ways:

1. Local-file DB backed mempool. This will allow restarts, but requires attached storage to be managed. Attached storage isn't great for our cloud infrastructure. This may be a useful modality for if/when we integrate Rundler with block builders.
2. Redis backed mempool. Allows multiple clients to have a similar view over the mempool and allows us to manage the mempool without needing attached storage. Needs simple coordination between clients.

We've decided to build a Redis-backed mempool to support the private mempool use case.

**Comment by dancoombs** [comment]
Blocked by #75.

Also potentially blocked by some changes required in the mempool to support multiple builders without invalidating each other (UO locking, etc.). We should do the design work up front in order to ensure this interface is as stable as possible.

**Comment by tadad** [comment]
are there any plans of reopening this or providing some equivalent functionality for a persistent mempool?

**Comment by dancoombs** [comment]
There are no current plans to implement this. We've decided to treat our mempool similar to how a node treats its mempool, as an in memory only data structure. Persistence can be built a layer above the bundler via a resubmission queue if strong persistence is required.

That being said, we are open to contributions and if someone wants to contribute an implementation of `Mempool` that uses Redis we would consider merging it.
