### ISSUE TITLE
ci: release pipeline with cross-arch builds

### ISSUE THREAD

**Issue by dancoombs** [alchemyplatform/rundler#421]
**Describe the feature**
Build a release pipeline that:

1. Runs release level testing
2. Increments the version
3. Publishes a new CHANGELOG
4. Builds docker containers for cross-arch
5. Uploads docker containers

This should be done automatically from the `release/*` branches upon branch creation (major/minor versions) or new merges (only fix versions) or manually.

**Comment by 0xfourzerofour** [comment]
https://github.com/cross-rs/cross/issues/724

There seems to be an issue when running cross in conjunction with build scripts, a long running issue that is yet to be solved. I am going to try an alternative or manual building of respective platforms

**Comment by 0xfourzerofour** [comment]
Mostly complete, just need to include binary gpg signatures like reth does

https://github.com/alchemyplatform/rundler/tree/josh/release-pipeline
