### ISSUE TITLE
Add rust-toolchain.toml

### ISSUE THREAD

**Issue by 0xfourzerofour** [alchemyplatform/rundler#459]
**Describe the feature**
We should pin rundler to a specific version of rust so that users do not get compilation errors if they are using the incorrect version that we have tested on.

**Comment by dancoombs** [comment]
Can you think of any reason why we would need to pin to a rust version for anything other than lints? Rust should never be backwards incompatible, and if it is we should know about it.

Maybe instead we just set the `msrv` in `clippy.toml` https://github.com/rust-lang/rust-clippy#specifying-the-minimum-supported-rust-version

**Comment by 0xfourzerofour** [comment]
Yeh that is a good point, removes the need for another file
