### ISSUE TITLE
Non-compliant Storage Access Restrictions

### ISSUE THREAD

**Issue by nlordell** [alchemyplatform/rundler#480]
Sorry if this is already captured in an existing issue. Also note that I am using `runder` over Alchemy and not running it locally.

I believe there may be an issue with slot restrictions in the `validateUserOp` simulation. In particular, ERC-4337 specifies a "slot associated with an address `A`" to be:

```
Slots of type `keccak256(A || X) + n` on any other address. (to cover `mapping(address => value)`, which is usually used for balance in ERC-20 tokens). `n` is an offset value up to 128, to allow accessing fields in the format `mapping(address => struct)`
```

From my understanding, all slots associated with the account (user operation `sender` field) are allowed to be accessed as part of `validateUserOp`, regardless of which contract they are on.

Additionally, the spec puts **no restriction on `X`**, which notably means that things like `mapping(key => mapping(address => value))` should also be supported as the accessed slot is:
```
keccak256(address || keccak256(key || mapping_slot))
  <=> keccak256(A || X) + n
      where A = address
            X = keccak256(key || mapping_slot)
            n = 0
```

However, I noticed that when submitting user operations that access such slots, that the following error is returned (user operation request included 👇):

```ts
{
  code: -32505,
  message: 'entity stake/unstake delay too low',
  data: {
    entity: { account: '0x0C13AF2986b1bf9E082cd66fA49229D64D73E21A' },
    minimumStake: '0x16345785d8a0000',
    minimumUnstakeDelay: '0x15180'
  }
}
```

I would expect such a user operation to be allowed. Removing the [storage access](https://goerli.etherscan.io/address/0x93aa2f6d83D668Cc50e2Af1a37EB049bee6A69b2#code#F26#L76) (commenting it out for example) causes the bundler to accept the user operation once again.

### Sample `eth_sendUserOperation` Request

The following `eth_sendUserOperation` demonstrates the issue. It was done on **Görli**.

<details><summary><code>request.json</code></summary>

```json
{
  "method": "eth_sendUserOperation",
  "params": [
    {
      "nonce": "0x00",
      "callData": "0x7bb3742800000000000000000000000002270bd144e70ce6963ba02f575776a16184e1e600000000000000000000000000000000000000000000000000005af3107a4000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "verificationGasLimit": "0x076ca6",
      "preVerificationGas": "0xc820",
      "callGasLimit": "0x6000",
      "maxFeePerGas": "0x3b9aca20",
      "maxPriorityFeePerGas": "0x3b9aca00",
      "initCode": "0x4e1dcf7ad4e460cfd30791ccc4f9c8a4f820ec671688f0b900000000000000000000000041675c099f32341bf84bfc5382af534df5c7461a0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001e4b63e800d000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000010000000000000000000000008483eb040e5c0a24a34281f5fe7cb662c800aabb000000000000000000000000000000000000000000000000000000000000014000000000000000000000000093aa2f6d83d668cc50e2af1a37eb049bee6a69b20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000feb6565bdd4aec9bd836f3ec7c7c0ffa79d025a400000000000000000000000000000000000000000000000000000000000000648d0dc49f0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000093aa2f6d83d668cc50e2af1a37eb049bee6a69b20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "paymasterAndData": "0x",
      "sender": "0x0C13AF2986b1bf9E082cd66fA49229D64D73E21A",
      "signature": "0x8e8087941cc796b08d52ee65e1569d0b284308b5ef1bad4c2d41c454fb09e7f41878724b598f5898017dfbea533b0d17cde7d7805a848d555eb767cd0106ea1b1c"
    },
    "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
  ],
  "id": 4337,
  "jsonrpc": "2.0"
}
```

</details>

**Comment by nlordell** [comment]
I did some digging and it _appears_ to be this condition that is causing `rundler` to think that stake is required:

https://github.com/alchemyplatform/rundler/blob/ed31bd8a9ae80d47b4d4c38427617163ded9f0e4/crates/sim/src/simulation/simulation.rs#L718

As far as I can gather, this is implementing some rules on limiting [**global** entity storage access](https://eips.ethereum.org/EIPS/eip-4337#un-staked-entities) (I may be wrong, this is just what I grokked from reading the code and the spec).

However, AFAIU this restriction should just apply to global entities and not the `sender` (which is the entity the error is being produced for - in the linked example request and error, the `userOp.sender == entity.account`). Doesn't that mean that the condition should be something like:

```rust
        if entity_address == sender_address || accessed_address == entry_point_address || !is_unstaked_wallet_creation {
            StorageRestriction::Allowed
        } else {
            StorageRestriction::NeedsStake
        }
```

**Comment by nlordell** [comment]
I can confirm that manually deploying the account and then sending the user operation works. In other words, it seems that specifying `initCode` adds additional storage restrictions on `validateUserOp`.

**Comment by 0xfourzerofour** [comment]
Thank you for reaching out, I will have a look at this today

**Comment by dphilipson** [comment]
Note that according to the spec, if the user op is creating the account (that is, if it has nonempty `initCode`), then the op cannot access the `sender`'s associated storage unless the factory is staked. See the second bullet point [here](https://github.com/ethereum/ercs/blob/master/ERCS/erc-4337.md#un-staked-entities).

Does that explain the behavior you're seeing?

**Comment by 0xfourzerofour** [comment]
Yeh, I think the error message is incorrect and not the logic but just making sure

**Comment by dphilipson** [comment]
You're right! The error message is indeed a bug. I looked over our code and I believe that while the error message is wrong, the rejection behavior is correct.

I completely agree that this section of the spec is very confusing. This caused a lot of confusion for us when we were implementing the rundler, and we actually asked the authors for clarification on the exact same point. This section of the spec has been modified a lot over time, which probably contributes to some of the confusion on global entities vs entities.

**Comment by dphilipson** [comment]
Correction: it appears our bug is not just in the error message, and it expects the wrong entity to be staked. Fix is incoming.

**Comment by 0xfourzerofour** [comment]
@nlordell just to updated you, I have a working version but I just need to validate before it is merged
