### ISSUE TITLE
[builder] Expose staking information of aggregator in bundle proposer

### ISSUE THREAD

**Issue by alex-miao** [alchemyplatform/rundler#515]
**Describe the feature**
Expose the staking information of the aggregator we are penalizing in the bundle proposer entity rejection flow. Right now we are defaulting to penalizing the aggregator as an unstaked entity. https://github.com/alchemyplatform/rundler/pull/494/files#r1396774296

**Comment by dancoombs** [comment]
We're only going to support whitelisted aggregators - no need for stake.
