### ISSUE TITLE
Error code: -32000, message: execution timeout

### ISSUE THREAD

**Issue by smakni** [alchemyplatform/rundler#544]
I have a require in my _validateSignature override witch contain the require bellow:

require (
    equal(getRsaModulusString(kid), modulus),
    "Modulus does not match"
);

function getRsaModulus(
		string memory kid
	) internal view returns (string memory modulus) {
		modulus = keys.getModulus(kid);
	}

The keys variable is an external contract.

When I try to send and operation with the method: 'eth_sendUserOperation' i run into this error:
{
  jsonrpc: '2.0',
  id: 1,
  error: {
    code: -32603,
    message: "(code: -32000, message: execution timeout at e (<eval>:1:2753(56))    in server-side tracer function 'step', data: None)"
  }

**Comment by dancoombs** [comment]
This looks to be a timeout error coming back from the node. Rundler uses a complex tracer during validation that can take multiple seconds to run depending on the complexity of the validation. It looks like this code is doing some complex cryptography, so this could be the case.

You should try raising the RPC timeout on your node.

**Comment by pilagod** [comment]
@dancoombs I bump into the same problem, but I am using the node registered on alchemy dashboard. Is it possible to raise the timeout for it?

**Comment by dancoombs** [comment]
It is not possible using the Alchemy RPC. The Alchemy RPC also doesn't support custom tracing so you'll have to run in `unsafe` mode.

Your best bet when trying to run Rundler that can do gas estimation and simulation for complex user operations is to run a dedicated node.

**Comment by pilagod** [comment]
I got it, thank you so much for the explanation 🙌
