### ISSUE TITLE
invalid tracer value, data: None

### ISSUE THREAD

**Issue by EvanChain** [alchemyplatform/rundler#650]
**Describe the bug**
Err while send uo to rpc node.

**To reproduce**
start a local node with commad:
RUST_LOG=debug ./rundler node --node_http https://arb-sepolia.g.alchemy.com/v2/xxxxxx --builder.private_key xxxxxx --chain_spec ./arbitrum_sepolia.toml

**Expected behavior**
Execute uo.

**Logs**
DEBUG rundler_utils::log: s: "failed to add op to the mempool: Internal((code: -32602, message: invalid 3rd argument: options 'tracer': invalid tracer value, data: None)\n\nCaused by:\n    (code: -32602, message: invalid 3rd argument: options 'tracer': invalid tracer value, data: None))"

**Additional context**
rustc 1.75.0

I trace the code executing to uo_pool.rs, the err looks like occured while getting sim_result.

line 381
let sim_result = self
            .simulator
            .simulate_validation(op.clone(), None, None)
            .await?;

**Comment by dancoombs** [comment]
Alchemy doesn't support custom tracers in its public API, which Rundler needs to run simulations. You'll need to run your own node to run Rundler.

In the upcoming Rundler 0.2 you'll be able to skip simulations (not recommended for production) with UNSAFE mode, which can be run on a public Alchemy API.
