### ISSUE TITLE
Build Failure Due to Rundler Submodule Pointing to Invalid Commit

### ISSUE THREAD

**Issue by prajwolrg** [alchemyplatform/rundler#763]
**Describe the bug**

Building the project with rundler as a dependency fails due to an issue with a submodule. The problem appears to be that the submodule at https://github.com/alchemyplatform/rundler/tree/main/test/spec-tests/v0_7 is pointing to a commit that does not exist in any branch.

**To reproduce**
1. Clone the repo: https://github.com/prajwolrg/rundler-script
2. Run `cargo build`

**Expected behavior**
The project should build successfully without errors.

**Logs**
```
error: failed to get `rundler-types` as a dependency of package `rundler-script v0.1.0`

Caused by:
  failed to load source for dependency `rundler-types`

Caused by:
  Unable to update https://github.com/alchemyplatform/rundler.git

Caused by:
  failed to update submodule `test/spec-tests/v0_7/bundler-spec-tests`

Caused by:
  object not found - no match for id (032e69d598c3cdf09b27b58eb6ee294e4d1580be); class=Odb (9); code=NotFound (-3)
```

**Additional context**
This issue might be resolved by updating the submodule to point to a valid commit. I can open a PR to address this if needed.

**Comment by e4coder** [comment]
Hey there,

Any update on this? i am stuck and unable to build the rundler. in production we are using a fork of rundler from march and that builds successfully. but now due to this we are unable to upgrade
