### ISSUE TITLE
[alloy] Implement a retry Tower service layer with exponential backoff

### ISSUE THREAD

**Issue by dancoombs** [alchemyplatform/rundler#786]
**Describe the feature**
Alloy uses Tower as its network client stack. It has an existing retry client, but its [implementation](https://github.com/alloy-rs/alloy/blob/main/crates/transport/src/layers/retry.rs) looks to be very specific to Anvil forking. We can use that implementation as a basis for a custom retry layer we control.

**Comment by andysim3d** [comment]
after comparing ether.rs and alloy's retry middleware, their retry logic are identical. so it should be good for now to use the alloy retry middleware.
