### ISSUE TITLE
[alloy] Add unit tests to alloy providers where applicable

### ISSUE THREAD

**Issue by dancoombs** [alchemyplatform/rundler#789]
**Describe the feature**
The alloy provider module contains zero unit tests. Unit tests are difficult as the majority of the logic requires making network calls.

We should evaluate the module and add unit tests where applicable.

We should be careful not to over re-factor the code in order to make it unit testable. I'd prefer easily readable, modifiable, code vs. code with extra interfaces introduced just for testing. We can rely on integration testing to catch some of these cases.

I'd also like to avoid spinning up anvil instances just for unit tests, as that feels very heavy handed.

I'm okay if this ticket is closed with a no-op after evaluation.

**Comment by dancoombs** [comment]
See #820 for a few examples of where unit tests would be helpful

**Comment by andysim3d** [comment]
#826
