### ISSUE TITLE
[pool] Evaluate using Alloy event watchers for chain tracking

### ISSUE THREAD

**Issue by dancoombs** [alchemyplatform/rundler#809]
**Describe the feature**
Alloy has an event watching [feature](https://github.com/alloy-rs/alloy/blob/cf9a98fd7ed41f1e86af1d58d3eba9bc1c9799b0/crates/contract/src/event.rs#L70).

We can consider replacing our chain tracking logic with this logic.

A few things to look out for:

1. Need to be able to watch for multiple event types on multiple contract addresses at the same time. Don't want to duplicate polling.
2. Needs to work on ws/http. We've defaulted to http in the past due to ws reliability/latency issues. We may want to re-evalutate this.
3. Needs to work with or without using `eth_getFilterChanges` as we've also seen reliability/latency/support issues with RPC providers implementations of this method.

**Comment by andysim3d** [comment]
Synced with @0xfourzerofour offline. the benefits of using the event watcher is we could remove the decoding code and simplified the topic handling logic [1]. But also we agreed the priority is not that high and could be postponed. 



[1]: https://github.com/alchemyplatform/rundler/blob/6c3691afdee003eac3e5e0bba144dd327978945f/crates/pool/src/chain.rs#L485-L524

**Comment by dancoombs** [comment]
> Synced with @0xfourzerofour offline. the benefits of using the event watcher is we could remove the decoding code and simplified the topic handling logic [1](https://github.com/alchemyplatform/rundler/blob/6c3691afdee003eac3e5e0bba144dd327978945f/crates/pool/src/chain.rs#L485-L524). But also we agreed the priority is not that high and could be postponed.

I still fail to see how the event watcher could be used in a way that can handle reorgs properly, without adding a bunch of complexity.

**Comment by 0xfourzerofour** [comment]
> > Synced with @0xfourzerofour offline. the benefits of using the event watcher is we could remove the decoding code and simplified the topic handling logic [1](https://github.com/alchemyplatform/rundler/blob/6c3691afdee003eac3e5e0bba144dd327978945f/crates/pool/src/chain.rs#L485-L524). But also we agreed the priority is not that high and could be postponed.
> 
> I still fail to see how the event watcher could be used in a way that can handle reorgs properly, without adding a bunch of complexity.

To be clear here, I said that the decoding logic would be cleaner as we have that out of the box at compile time from the event within the `sol!` macro. In terms of the chain listener we would still need to use the block watcher and make an eth_getLogs query however the logs query can be cleaned up by using the filters that come out of the macro while keeping all the same reorg handling
